FROM apache/airflow:2.8.1-python3.10

USER airflow

COPY requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir --user -r /tmp/requirements.txt

COPY dags/ /opt/airflow/dags/

WORKDIR /opt/airflow
